import Head from 'next/head'
import Link from 'next/Link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Outfit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Please click{" "}
        <Link href="/products">
          the link!
        </Link>
      </h1>

      
    </div>
  )
}
